Simulating an error

diff --git a/.github/workflows/whatever.yml b/.github/workflows/whatever.yml
--- a/.github/workflows/whatever.yml
+++ b/.github/workflows/whatever.yml
@@ -21,5 +21,8 @@ jobs:
       - name: Build 🏗️
         run: npm run build
 
+      - name: Simulate an error
+        run: echo "About to fail" ; exit 1
+
       - name: Test 🚨
         run: npm test
